### ISSUE TITLE
I used your EFI

### ISSUE THREAD

**Issue by Shiyang-Wang** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#1]
I used your EFI，but I my audio was sometimes unable to use when I start my system or restart, it is very unstable. Finally, I used voodooHDA.kext, ALCPlugFix and CodecCommander.kext and now it is very stable without any noise. The only problem  is that it can not switch between headphone and speaker automatically. It is tricky that all my 3 computers are unstable when I use native APPLEHDA, I changed all of them to voodooHDA and all of then are very stable.

**Comment by Juan-VC-gh** [comment]
I do know about this issue and have been testing an alternative to ComboJack to see if that is the problem.

I have rushed an update to see how it works for you, I have not had the issue since using the new solution but It might still happen rarely and I am not yet aware of the cause.

Try the following:

Look for verbstub.kext in /Clover/kexts/Other/ if it is present, delete it. Otherwise you could have it in /Library/Extensions/ so browse and remove it.

Remove ComboJack from /usr/local/sbin
Remove hda-verb from /usr/local/sbin
Remove ComboJack folder from /usr/local/share/
Remove com.XPS.ComboJack.plist from /Library/LaunchDaemons/

Install CodecCommander.kext from Rehabman (kext included in the Jack_Fix folder) and install it with your preferred kext installer to /Library/Extensions/

 Download the Catalina Hackintosh repo as a zip to /Downloads/, copy new config.plist and replace the old one in /Clover/.  Return to the master repo folder and finally run Install.command  found in Jack_Fix and reboot!

If audio still is not working try

sudo kextcache -I /

Reboot again.

If you did not have HiDPI resolutions they will be enabled, for the first time things will look huge but choose your favorite resolutions from the display menu and things won't look huge after that.

**Comment by Shiyang-Wang** [comment]
Thank you！！！
