### ISSUE TITLE
Headphone jack line in not working

### ISSUE THREAD

**Issue by neliets** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#33]
Hello!

First of all, huge thanks for this resource! I also wanted to add, that your setup works perfectly on Dell G5 5578, i7-8750h, 32gb ram, 1tb Adata NVMe.

But I have only one issue - headphone jack line-in does not work. I also tried some common methods online, but they did not seem to work and broke my audio completely.

Do you have any suggestions?

**Comment by Juan-VC** [comment]
Hey, nice to know you were able to set up macOS on your laptop as I have never tested on a G5! Did you get it working that I got a notification the issue was closed?

To be honest jack has been the most painful thing to get work, I used to have a utility that polled if the jack pin changed to fix it, and it was using a deprecated kext and drained a LOT of battery. I decided to try some layout ids for ALC256 and surprisingly layout 17,21,66 made jack worked like a charm, audio in general I found was better with layout 21 but there's still a problem with jack and is that you can sometimes lose jack audio when sleeping but not always, it sometimes comes back. I believe it is still an active problem and I have not had that much time to see what can be done if you still do not have it working I recommend trying the above-mentioned layout ids or even more after that in case your codec map is different, also confirm before trying the layouts that your laptop does carry an ALC256 codec.

Briefly, I would say jack audio works partially and would someday need a fix/workaround
