### ISSUE TITLE
Intel network

### ISSUE THREAD

**Issue by LYMDLUT** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#34]
someone said recently that the intel network could be used, and also the bluetooth.but when I put the kext into the oc configurator, it can not work, could you help us.we don't change our intel wireless network.

**Comment by LYMDLUT** [comment]
Thanks a lot,my English is poor and I hope you will not mind this.I think this resource is the best I have used ever,and I believe it will be better.Thank you for your excellent job!

**Comment by Juan-VC-gh** [comment]
Cool, you got macOS working! I have seen advances with intel wifi and Bluetooth, I haven't tried any and do not have an intel card with me anymore so it is up to you to test it. I suppose you found these repos [Intel Wifi](https://github.com/OpenIntelWireless/itlwm) and [Intel Bluetooth](https://github.com/OpenIntelWireless/IntelBluetoothFirmware)

**Comment by Juan-VC-gh** [comment]
Any is a considered a stable solution because of some packet loss and bugs, if you want to get any of those test projects working you must first delete AirportBrcmFixup.kext, BrcmBluetoothInjector.kext, BrcmFirmwareData.kext found in /EFI/OC/Kexts, and these kexts entries in config.plist found in Kernel->Add like the one shown in the image. The entries that should be removed if counting from zero are 2,3,6,7,8 which are all related to Broadcom Wifi and Bluetooth
<img width="1440" alt="Screen Shot 2020-09-19 at 9 48 01 AM" src="https://user-images.githubusercontent.com/30065686/93671079-4c772280-fa5d-11ea-835d-0a5578f25527.png">

**Comment by Juan-VC-gh** [comment]
After that copy the test intel Wifi and Bluetooth kexts to /EFI/OC/Kexts and also add entries like the one I have in the image above in config.plist->Kernel->Add to let OpenCore know you want to load those kernel extension, good luck!

**Comment by Juan-VC-gh** [comment]
I just read you must configure networks either manually editing some properties in a plist file or with a wifi management app but it cannot use macOS native one, that's where [HeliPort](https://github.com/OpenIntelWireless/HeliPort) comes in

**Comment by cyinen** [comment]
Now I can use inter wifi, but the inter Bluetooth can't work correctly. I'm so sad!

**Comment by Juan-VC-gh** [comment]
That is a driver issue and intel drivers are known to have bugs at the moment. Basic stuff may work but Airdrop or Handoff I believe do not.
