### ISSUE TITLE
Video Output and Bluetooth Questions

### ISSUE THREAD

**Issue by LurnD** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#37]
Hello Juan-VC, I have a BCM94352z(FRU PN:04X6020) card, so do I need modify something in config or I can use it directly. 
I also want to know the HDMI output is connected with NVIDIA so it can't output video, can I use Thunderbolt 3(use DP protocol
) to output Video to my screen. I try this method successfully in my Intel NUC, but I want to know whether G7 can work with it?

**Comment by LurnD** [comment]
By the way, the Lenovo module(04X6020) and the Dell module (DW1560) are the same when I use it on my Thinkpad T470 Laptop. But has some little questions, for example Bluetooth will lose when sleep, and it can only unlock my Mac with my Apple Watch the first time, then it will fail. So I want to know, how this card perform on Dell G7.

**Comment by Juan-VC-gh** [comment]
Hey! So for the video output, yes the Thunderbolt 3 port can be used with no issues, for the HDMI port it cannot drive output video since it is an optimus card which works with a software mux and there is no driver for it, for a discrete graphics card to work it requires drivers + hardware mux. Anyways, the tb3 can be used with any tb compatible display. 
For the broadcom card, I cant test an apple watch since I don't own one but I think it will work perfectly, my laptop can sleep and wake with no airdrop/handoff issues. Did you check if the firmware is being correctly injected on boot? Because even if the BCM94352Z is not natively supported, the linux drivers port work just as good as a native supported card.

**Comment by LurnD** [comment]
Hello Juan, thank you for your answer. I am waiting for a new ssd and mechanical drive to install hackintosh. For Broadcom Card, I want to know whether two cards have some differences? For Apple Watch unlock, I think it will only successfully work with apple native card.

**Comment by Juan-VC-gh** [comment]
I sometime and somewhere (i think it was on github) that non-native broadcom cards work with the apple watch perfectly if the firmware was being loaded properly but I can't tell, have never tested with a watch

**Comment by shreyasrawat** [comment]
Yeah the dongle works for me thanks!
