### ISSUE TITLE
Failed to dual boot macOS and Windows

### ISSUE THREAD

**Issue by LurnD** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#38]
Hello Juan-VC, I am here again lol. I installed Catalina and it worked fine on my friend's G7 with BCM94352z (Lenovo version). But I encountered a weird problem. This G7 works in RAID mode, I transfer origin Windows  system by Aomei Assistant. After I transferred windows to M.2 SSD(macOS also installed on it), in OC boot page, I can choose macOS, Recovery and windows. But when I chose windows selection, It can't boot into it and stuck at some dot looped before enter windows login interface. I tested if I turn on RAID mode, Windows can work fine.
I am wondering how to dual boot macOS and Windows(with my using version, much working data and software, not possible to reinstall a new version) with RAID mode off .
My currently used SSD(windows install on, Samsung PM981 512G which can't boot macOS), the replaceable one is WD SN550 1T (macOS and Windows installed).

**Comment by LurnD** [comment]
Also wanted to know how Big Sur works?

**Comment by Juan-VC-gh** [comment]
Yes it is weird if it works in RAID mode and also that windows cannot be installed in AHCI, well if ot works in raid I see no problem leaving it like that! Also are you loading windows with OpenCore or a chain loader? Because ACPI tables for windows are not ready, I haven’t had the time or have been somewhat lazy so windows must be loaded with a chain loader like rEFInd.

About big sur, works as intented everything is fine except for some minor bugs in apps I believe is because they have not been updated. Also I need to update the hidpi script as big sur system files are all cryptographically signed and macOS works with snapshots so it is kinda tricky to modify the live system.

**Comment by LurnD** [comment]
Yes I am using OpenCore to boot Windows. So if I understand correctly, I can transfer windows to the new SSD and boot macOS and Windows in AHCI mode, but should config rEFInd to boot Windows correctly?

**Comment by Juan-VC-gh** [comment]
Yes, that is the idea. I gotta someday fix windows booting with oc but just have been lazy or busy.

**Comment by LurnD** [comment]
OK, thank you very much. I am gonna test rEFInd in the end of month. My friend had got his laptop back.

**Comment by Juan-VC-gh** [comment]
Dropped rEFInd for multi-boot, OC is the only one needed now

**Comment by LurnD** [comment]
Thanks I will test it and give you responses.
