### ISSUE TITLE
Audio have some cracking noise after waking from sleep

### ISSUE THREAD

**Issue by vinhtq115** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#41]
I noticed that if I put my Hackintosh to sleep and wake them, audio will have cracking noise when I listen to music, happens about every 15-30 seconds i guess. However, if I do a complete shut down, the problem is gone and it happens again if I put the laptop to sleep.

Anyone having this issue?

**Comment by Juan-VC-gh** [comment]
Right, there is that noise because of an issue with the 3.5mm jack. I have been preparing a commit will try to push it today which ComboJack should fix it. Note that ComboJack is removed with a cleanmymac file cleanup so if you use it, the post-install script would need to be rerun

Hope that helps!

**Comment by 13thdemarch** [comment]
that's weird 🤔
my G7 after wake or sleep everything is still okay.
also, try other layout-id. Even id 21 will give you free external output but there is an issue with cpu performance, also audio will be crashed if you let it afk or play audio more than a day

**Comment by Juan-VC-gh** [comment]
I think my last ComboJack upload wasnt working so it did not recover from sleep. id 14 with the recently uploaded ComboJack or id 21 should work

**Comment by Juan-VC-gh** [comment]
Audio jack is fixed with newest ComboJack
