### ISSUE TITLE
Question about SSDT-TYPC-TB3.aml

### ISSUE THREAD

**Issue by vinhtq115** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#47]
Hi. What is `SSDT-TYPC-TB3.aml` for? Also, I noticed that it is currently disabled in `config.plist`. Is that intended?

**Comment by Juan-VC-gh** [comment]
Yes it is intended as mentioned [here](https://juan-vc.github.io/oc-g7-guide/post-installation/setup-oc.html) it enables tb3 hot-plug that allows to use some tb3 devices even when plugged after booting. It is disabled by default because to get hot-plug working we require to have the tb3 controller always-on-power like macOS expects on a real mac and will consume more energy, main reason why I decided to leave the decision to the user.

**Comment by vinhtq115** [comment]
Thank you.
