### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by junguoguo2017** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#48]
1.SSDT-TyPC-TB3.AML and IOElectrify are open according to the documentation.but Thunderbolt 3 doesn't work。 
2.Startup interface system selection is very slow

**Comment by vinhtq115** [comment]
> 2.Startup interface system selection is very slow

In `UEFI` -> `Input`, try set the `KeyForgetThreshold` to `5`.

Here's mine for reference:
```
<key>Input</key>
<dict>
	<key>KeyFiltering</key>
	<false/>
	<key>KeyForgetThreshold</key>
	<integer>5</integer>
	<key>KeySupport</key>
	<true/>
	<key>KeySupportMode</key>
	<string>Auto</string>
	<key>KeySwap</key>
	<false/>
	<key>PointerSupport</key>
	<false/>
	<key>PointerSupportMode</key>
	<string></string>
	<key>TimerResolution</key>
	<integer>50000</integer>
</dict>
```

**Comment by Juan-VC-gh** [comment]
> 1.SSDT-TyPC-TB3.AML and IOElectrify are open according to the documentation.but Thunderbolt 3 doesn't work。
> 2.Startup interface system selection is very slow

1. Settings must be changed according to the documentation, tb3 hot plug is disabled by default to save energy but the required items are provided so it is simple for a user to enable it if needed.
2. With the OC update from this month, I will implement @vinhtq115 suggestion because it really feels somewhat unresponsive.

**Comment by 13thdemarch** [comment]
1. If you want to get hotplug work, make sure **Thunderbolt Auto Switch** is set to **Native Enumeration** in BIOS.
2. Leave everything to default in **Input** section. Try to reset BIOS to default and re-config, then reset nvram. Also disable the Legacy Boot in BIOS. It can't be fast like other machines because nvram on this G7 is very weak, but it's smoothy to use.
@Juan-VC Also man, I forgot to tell you. Since macOS 11.3.1, because Apple has changed some thing weird about USB, so the IOElectrify kext and Type-C hotplug SSDT sometimes will cause kernel panic. I already deleted them in my repo.

**Comment by junguoguo2017** [comment]
> 1. If you want to get hotplug work, make sure **Thunderbolt Auto Switch** is set to **Native Enumeration** in BIOS.
> 2. Leave everything to default in **Input** section. Try to reset BIOS to default and re-config, then reset nvram. Also disable the Legacy Boot in BIOS. It can't be fast like other machines because nvram on this G7 is very weak, but it's smoothy to use.
>    @Juan-VC Also man, I forgot to tell you. Since macOS 11.3.1, because Apple has changed some thing weird about USB, so the IOElectrify kext and Type-C hotplug SSDT sometimes will cause kernel panic. I already deleted them in my repo.

I got it;think you

**Comment by Juan-VC-gh** [comment]
> * If you want to get hotplug work, make sure **Thunderbolt Auto Switch** is set to **Native Enumeration** in BIOS.
> * Leave everything to default in **Input** section. Try to reset BIOS to default and re-config, then reset nvram. Also disable the Legacy Boot in BIOS. It can't be fast like other machines because nvram on this G7 is very weak, but it's smoothy to use.
>   @Juan-VC Also man, I forgot to tell you. Since macOS 11.3.1, because Apple has changed some thing weird about USB, so the IOElectrify kext and Type-C hotplug SSDT sometimes will cause kernel panic. I already deleted them in my repo.

Oh I did not know some changes in 11.3.1 broke IOElectrify, will probably remove the hot plug files, thanks for the info @rex-lapis
