### ISSUE TITLE
Color Banding

### ISSUE THREAD

**Issue by mrzooit** [Juan-VC/Hackintosh-macOS-Dell-G7-7588#5]
I'm not sure this is the place to ask this,

is it possible to fix the color banding artifacts (more pronounced in Launchpad)?

Thank you for your work!

**Comment by Juan-VC-gh** [comment]
Can you attach some pictures?

**Comment by mrzooit** [comment]
It looks worse than it is to the eye.
![photo](https://user-images.githubusercontent.com/62580806/77618669-7f5cb580-6f15-11ea-8e29-db53d357ee33.jpeg)

**Comment by Juan-VC** [comment]
It might be a framebuffer, not sure. Using latest recommended framebuffer for CoffeLake iGPU per whatevergreen's.

Tried extracting the display EDID from Windows and macOS, they were both exactly the same. Then forced injecting the display EDID yet it seems it is still present.

I don't notice it since I use Spotlight to open apps. 
Gotta have to be fixed later.

**Comment by Juan-VC** [comment]
It might be a framebuffer, not sure. Using latest recommended framebuffer for CoffeLake laptop iGPU per whatevergreen's.

Tried extracting the display EDID from Windows and macOS, they were both exactly the same. Then forced injecting the display EDID yet it seems it is still present.

I don't notice it since I use Spotlight to open apps. 
Gotta have to be fixed later.

**Comment by Juan-VC-gh** [comment]
It might an issue with the framebuffer, not sure. Using latest recommended framebuffer for CoffeLake laptop iGPU per whatevergreen's Intel info.

Tried extracting the display EDID from Windows and macOS, they were both exactly the same. Then forced injecting the display EDID yet it seems it is still present.

I don't notice it since I use Spotlight to open apps. 
Gotta have to be fixed later.

**Comment by mrzooit** [comment]
OK, thank you! (Do I close the issue?)

**Comment by Juan-VC-gh** [comment]
I usually do. Will leave it there to try something else later or I will close it myself if I am too lazy to try.

**Comment by MallyMall** [comment]
I've noticed this as well. It doesn't happen with external displays (dock). Just the laptop screen.

**Comment by mrzooit** [comment]
Hello, do you know if this is fixed if you use this Open Core? Also, I'm a _total noob_, and setting up the Hackintosh via Clover was enough of a chore for me — and really only possible because of your guide —, do you think I should migrate to Open Core?

**Comment by Juan-VC-gh** [comment]
It is not fixed and migrating to OpenCore with a working machine is easy. Copy the OC folder inside EFI (where you also have the Clover folder) and create a boot entry for OpenCore.efi and that’s it! You could then try setting rEFInd and to disable CFG-Lock.

Yes I recommend migrating to OpenCore, good luck!

**Comment by mrzooit** [comment]
Thank you!

**Comment by junguoguo2017** [comment]
I have the same problem,

**Comment by junguoguo2017** [comment]
I found an article that you can refer to to see if it is useful. http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1817073

**Comment by Juan-VC-gh** [comment]
For some reason, this issue is a laptop screen problem and not the actual OS setup. Best and might be the only solution is replacing the laptop screen.
